### ISSUE TITLE
Magic bugs

### ISSUE THREAD

**Issue by Russell2023** [atlasgames-repo/fortress-defense#104]
After clicking the magic button and clicking the area that I wanted to use the magic on, It didn't work and the magic didn't apeare.

**Comment by m-nt** [comment]
- In which branch is this bug happening !?   
- plz provide a video clip (with all unity panels) of the bug too.

**Comment by Russell2023** [comment]
in New-Levels

**Comment by Russell2023** [comment]
https://github.com/atlasgames-repo/fortress-defense/assets/103450629/db92907f-3f77-4541-a71d-7a9db525220f

**Comment by Russell2023** [comment]
while clicking on the yellow areas on the ground, the magic won't appear

**Comment by m-nt** [comment]
Solved in this commit: 030ea197d51610e333cb47d6fb8b60112dd973cf
