### ISSUE TITLE
Level Generator Bug

### ISSUE THREAD

**Issue by Russell2023** [atlasgames-repo/fortress-defense#109]
there is three changeable custom values in level generator. We have **Custom Health**. **Custom Speed** and **Custom Attack Damage**. Custom Speed is fine and it works perfectly. But setting the Custom Health value to anything will cause the boss to die faster. Setting Custom Attack damage value to anything is useless as well and it doesn't do anything.

![fortress-defense - Playing atlas - PC, Mac   Linux Standalone - Unity 2020 2 5f1 Personal _DX11_ 12_11_2023 6_24_42 PM](https://github.com/atlasgames-repo/fortress-defense/assets/103450629/993aa579-e8b0-4950-9af2-d94612fd544d)

**Comment by m-nt** [comment]
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/b5dd5aa6-1c10-43af-a0bc-b3425f891610)
###### The logic behind this is in the picture above.   
- If custom values are greater than `zero`, enemies corresponding property will change to the custom value.   
- This is for level 10,  and its working just fine.   
- just tone the health, damage etc... of bosses.   
#### and another think.
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/432e254d-5653-4cc9-965f-a394d06ea05a)
###### there is some cool properties in enemies, don't forget to use them. 

#### for example 
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/ee3a99f1-3421-41e1-9cc1-d272f9d156b3)
- if you set a weakness of type poison to an enemy with respect to its multiplier the damage from any poison will be increases.
