### ISSUE TITLE
Boss Damage

### ISSUE THREAD

**Issue by Russell2023** [atlasgames-repo/fortress-defense#110]
Boss fights don't have any damages and even if they get so close. they won't effect the castle health at all.

**Comment by m-nt** [comment]
I checked the boos and mini-boos its working as expected, the problem is its health is very low, use custom health and damage to customize the boos/mini-boos @Russell2023

**Comment by Russell2023** [comment]
checkout the video:


https://github.com/atlasgames-repo/fortress-defense/assets/103450629/c088e51f-bcfc-4f91-8a38-ef0e17ff0e45

**Comment by m-nt** [comment]
مشکل editor level رو پیدا کردم که چرا save نمیکنه، prefab ویرایش میشه ولی تا خود prefab رو select نکنی تغییرات ذخیره نمیشه، خیلی عجیبه ولی مشکل از سیستم مدیریت پنجره های یونیتیه، کاریش نمیشه کرد، الان بهترین راه برای ویرایش level ها باز کردن خود prefab توی prefab editor خود یونیتیه، برای ساخت لول جوواب میده این ادیتور.
الان من بررسی کردم دیدم اگه بعد از زدن دکمه Edit level و ذخیره، توی پنجره Project خود prefab اون level رو انتخاب نکنی تغییراتو ذخیره نمیکنه

**Comment by m-nt** [comment]
@Russell2023 
fixed in https://github.com/atlasgames-repo/fortress-defense/pull/103/commits/f492d35fa5e9d9581635028506311618644bece1
