### ISSUE TITLE
A new system for earning gold and gem

### ISSUE THREAD

**Issue by Russell2023** [atlasgames-repo/fortress-defense#88]

**Comment by Russell2023** [comment]
The game will give player gold and gem by using this new sytem.
Gem can be earne ONLY by playing events.
Gold can be earned by playing regular levels AND by achieving achievements.

**Comment by Russell2023** [comment]
The required formulas will be written in the future.

**Comment by Russell2023** [comment]
We can use the same codes we used to earn XP.

**Comment by m-nt** [comment]
میبندم اینو، یه issue مشابه داریم
