### ISSUE TITLE
Level Generator Error

### ISSUE THREAD

**Issue by Russell2023** [atlasgames-repo/fortress-defense#98]
This error happens after trying to save and export a new level. The error causes the "save and export" section to disappear.

**Visual Error:**
![fortress-defense - Playing atlas - PC, Mac   Linux Standalone - Unity 2020 2 5f1 Personal _DX11_ 12_8_2023 10_36_34 PM](https://github.com/atlasgames-repo/fortress-defense/assets/103450629/50bbdea6-22a4-4263-a2a0-f5ab47c22893)

**Error stack:**
NullReferenceException: Object reference not set to an instance of an object
LevelDataEditorWindow.OnGUI () (at Assets/Atlas games/Editor/LevelDataEditorWindow.cs:41)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <22954a70fcec46f29620f943d3d7bf23>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <22954a70fcec46f29620f943d3d7bf23>:0)
UnityEditor.DockArea.OldOnGUI () (at <22954a70fcec46f29620f943d3d7bf23>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0050475d167947ea9f166ad030caa84f>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by m-nt** [comment]
https://github.com/atlasgames-repo/fortress-defense/tree/98-level-generator-error
اینجا تستش کردم، توی پروسه save and export به ارروری بر نخوردم.
لطفا اگر حالت خاصی وجود داره که این اتفاق میوفته بگو، 
تنها حالتی که به اررور خورد برای من وقتی بود که کد های پروژه مجدد کامپایل میشه که با بستن و باز کردن Level Generator مشکل حل میشه.
باز هم میگم با جزئیات توضیح بده که اررور چطور تولید میشه، اینکه میگی دکمه save and export مشکل ایجاد میکنه من ارروری ندیدم و داره درست کار میکنه.

**Comment by Russell2023** [comment]
هیج حالت خاصی نداره.تنها زمانی که save and export فشرده میشه این اتفاق میفته. میتونم فایل ویدیویی بفرستم.

**Comment by Russell2023** [comment]
**Check the video below:**

https://github.com/atlasgames-repo/fortress-defense/assets/103450629/e900b89e-e421-4394-b017-974d3770743e

**Comment by Russell2023** [comment]
I fund another issue with the level generator. It sometimes resets the level info automaticly. When I upload a level prefab onto the level generator and I press load data, It resets all the data to the last level that I designed. This causes time lost :(

**Comment by m-nt** [comment]
- [x] - `Fixed Font issue`
