### ISSUE TITLE
Infinite Stop

### ISSUE THREAD

**Issue by Russell2023** [atlasgames-repo/fortress-defense#99]
There is a line of code that causes the current scene to stop after pressing play button. This error can be fixed by turning this line of code to a comment.

**Visual**
![AffectZoneButton cs - fortress-defense - Visual Studio Code 12_9_2023 10_49_31 PM](https://github.com/atlasgames-repo/fortress-defense/assets/103450629/ab1ed5df-0e31-4deb-9849-aac005059a31)

**Error Stack:**
4.98
UnityEngine.Debug:LogError (object)
AffectZoneButton:Update () (at Assets/_FD/Script/AffectZoneButton.cs:69)

**Comment by m-nt** [comment]
اررور از این لاین نیست این لاین Log عادیه در حالت Error ، اررور اصلی رو بفرست

**Comment by Russell2023** [comment]
warning 1:
Assets\_FD\Script\SpawnEnemyManager\LevelEnemyManager.cs(13,9): warning CS0414: The field 'LevelEnemyManager.currentWave' is assigned but its value is never used

warning 2:
Assets\Atlas games\Scripts\UI\Story\Story.cs(33,18): warning CS0414: The field 'Story._playing' is assigned but its value is never used

warning 3:
Assets\_FD\Script\GUI\GiftVideoAd.cs(10,10): warning CS0414: The field 'GiftVideoAd.allowShow' is assigned but its value is never used

warning 4:
Assets\_FD\Script\Player_Archer.cs(294,11): warning CS0414: The field 'Player_Archer.delayAutoShootCounter' is assigned but its value is never used

**Comment by Russell2023** [comment]
warning 5:
Assets\_FD\Script\Player_Archer.cs(293,11): warning CS0414: The field 'Player_Archer.delayAutoShoot' is assigned but its value is never used

warning 6:
Assets\_FD\Script\Player_Archer.cs(65,10): warning CS0414: The field 'Player_Archer.allowCheckAttack' is assigned but its value is never used

warning 7:
Assets\_FD\Script\ArrowProjectile.cs(212,10): warning CS0414: The field 'ArrowProjectile.isStop' is assigned but its value is never used

warning 8:
Assets\Editor\TipEditor.cs(166,26): warning CS0168: The variable 'e' is declared but never used

waring 9:
Assets\Atlas games\Editor\ExtendedEditorWindow.cs(11,12): warning CS0414: The field 'ExtendedEditorWindow.LevelEnemyManagerPath' is assigned but its value is never used

**Comment by Russell2023** [comment]
وارنینگها مشکلی ایجاد نمیکنن فقط بعد از حذف کد قبلی ظاهر میشن

**Comment by m-nt** [comment]
زیاد این warning  هارو جدی نگیر و اینکه لطفا سرچ کن اینارو توی گوگل، مثلا اولی داره میگه یه متغییری داری به اسم delayAutoShoot که هیچ وقت استفاده نشده، این مشکلی نیست فقط اخطار lsp سیشارپ هست.
